name: amd64_windows_gcc

on: [push, pull_request]

jobs:

  amd64_windows_gcc:
    runs-on: windows-2019
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - run: echo "::add-path::C:\\msys64\\usr\\bin"
    - run: gcc -v
    - run: make
    - run: file ./hello.exe
    - run: ./hello
