name: amd64_windows_clang

on: [push, pull_request]

jobs:

  amd64_windows_clang:
    runs-on: windows-latest
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - run: echo "::add-path::C:\\msys64\\usr\\bin"
    - run: pacman --version
    - run: pacman -Sy
    - run: pacman --noconfirm -S pacman-mirrors
    - run: pacman --noconfirm -S mingw64/mingw-w64-x86_64-clang
    - run: echo "::add-path::C:\\msys64\\mingw64\\bin"
    - run: clang --version
    - run: make
    - run: file ./hello.exe
    - run: ./hello
