name: armhf_linux_gcc

on: [push, pull_request]

jobs:

  armhf_linux_gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get -y -qq update
    - run: sudo apt install -y qemu-user
    - name: Prepare Dockcross
      run: |
        git clone --depth 1 https://github.com/dockcross/dockcross.git && cd dockcross
        docker run --rm dockcross/linux-armv7 > ./dockcross-linux-armv7
        chmod +x ./dockcross-linux-armv7
    - name: Verify tools version
      run: ./dockcross/dockcross-linux-armv7 bash -c '$CC --version'
    - name: make
      run: ./dockcross/dockcross-linux-armv7 make LDFLAGS=-static
    - run: file ./hello
    - run: qemu-arm ./hello
