name: i686_windows_clang

on: [push, pull_request]

jobs:

  i686_windows_clang:
    runs-on: windows-2019
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - run: echo "::add-path::C:\\msys64\\usr\\bin"
    - run: pacman --version
    - run: pacman -Sy
    - run: pacman --noconfirm -S pacman-mirrors
    - run: pacman --noconfirm -S mingw32/mingw-w64-i686-clang
    - run: echo "::add-path::C:\\msys64\\mingw32\\bin"
    - run: clang --version
    - run: which clang
    - run: make
    - run: file ./hello.exe
    - run: ./hello
