name: Build

on: [push, pull_request]

jobs:

  amd64_linux_clang:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y make clang
    - run: clang --version
    - run: CC=clang make
    - run: file ./hello
    - run: ./hello

  amd64_linux_gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y make gcc
    - run: gcc --version
    - run: CC=gcc make
    - run: file ./hello
    - run: ./hello

  amd64_linux_tcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y make tcc
    - run: tcc -v
    - run: CC=tcc make
    - run: file ./hello
    - run: ./hello

  amd64_macos_clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: cc --version
    - run: make
    - run: file ./hello
    - run: ./hello

  amd64_macos_gcc:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install gcc@9
    - run: gcc-9 --version
    - run: CC=gcc-9 make
    - run: file ./hello
    - run: ./hello
